"""
Customer Simulator — Order generation, payment simulation, and dispute handling.

This module implements the ``CustomerSimulator`` class responsible for simulating
customer interactions with the ERP system.  It is a leaf consumer in the
``app.external_world`` package, integrating with:

* **Statistical Models** — ``AmountDistribution`` for log-normal order amounts by
  customer tier (Small $500–$5 K, Medium $2 K–$50 K, Large $10 K–$500 K);
  ``OrderFrequencyModel`` for Poisson-based daily order counts with day-of-week
  effects; ``PaymentTimingModel`` for 5-segment mixture model payment dates;
  ``SelectionModel`` for 70/30 repeat/new product selection and revenue-weighted
  customer batch selection.
* **Behaviour Profiles** — ``BehaviorProfile`` drives per-customer payment
  segments, short-pay rates, dispute rates, and order patterns.
* **Event Bus** — publishes ``TransactionCreated`` (order generation) and
  ``DiscrepancyDetected`` (dispute creation) events for cross-subsystem
  coordination.

All public methods are async coroutines (no blocking I/O).  Reproducible seeding
is achieved via ``numpy.random.RandomState``.

Data Contracts:
    * ``CustomerSimulatorConfig``  — Pydantic V2 configuration model.
    * ``CustomerOrder``           — Order data with UUID default factory.
    * ``CustomerPayment``         — Payment data with short-pay tracking.
    * ``CustomerDispute``         — Dispute data with type and status fields.

References:
    - README.md lines 456–508, 526–528, 554–558, 583–585
    - AAP Section 0.5.1 Group 7 (CustomerSimulator specification)
    - AAP Section 0.7.1 (Pydantic V2 at subsystem boundaries, constructor injection)
    - AAP Section 0.7.3 (async, no blocking I/O)
    - AAP Section 0.7.6 (structlog JSON logging to stdout)
"""

from __future__ import annotations

import asyncio
from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, TYPE_CHECKING
from uuid import UUID, uuid4

import numpy as np
import structlog
from pydantic import BaseModel, Field

from app.external_world.behavior_profiles import BehaviorProfile, CUSTOMER_PROFILE_TEMPLATES
from app.events.event_types import TransactionCreated, DiscrepancyDetected

if TYPE_CHECKING:
    from app.statistical.amount_distributions import AmountDistribution
    from app.statistical.order_frequency_model import OrderFrequencyModel
    from app.statistical.payment_timing_model import PaymentTimingModel
    from app.statistical.selection_models import SelectionModel
    from app.events.event_bus import EventBus

# ---------------------------------------------------------------------------
# Module-level structured logger (AAP §0.7.6 — structlog to stdout)
# ---------------------------------------------------------------------------
logger = structlog.get_logger(__name__)


# ===========================================================================
# Pydantic V2 Configuration Model
# ===========================================================================


class CustomerSimulatorConfig(BaseModel):
    """Configuration for the ``CustomerSimulator``.

    All fields have sensible defaults so that ``CustomerSimulatorConfig()``
    produces a valid configuration out of the box.

    Attributes:
        default_payment_terms: Default payment terms string (e.g. ``"Net 30"``).
        dispute_resolution_days_min: Minimum days to resolve a dispute.
        dispute_resolution_days_max: Maximum days to resolve a dispute.
        short_pay_percentage_min: Minimum fraction deducted in a short-pay
            scenario (1 %).
        short_pay_percentage_max: Maximum fraction deducted in a short-pay
            scenario (10 %).
        order_line_items_min: Minimum number of line items per order.
        order_line_items_max: Maximum number of line items per order.
        dispute_types: Possible dispute type labels.
    """

    default_payment_terms: str = "Net 30"
    dispute_resolution_days_min: int = Field(default=5, ge=1)
    dispute_resolution_days_max: int = Field(default=30, ge=1)
    short_pay_percentage_min: float = Field(default=0.01, ge=0.0, le=1.0)
    short_pay_percentage_max: float = Field(default=0.10, ge=0.0, le=1.0)
    order_line_items_min: int = Field(default=1, ge=1)
    order_line_items_max: int = Field(default=20, ge=1)
    dispute_types: List[str] = Field(
        default_factory=lambda: ["pricing", "quality", "quantity", "service"]
    )


# ===========================================================================
# Customer Data Models (Pydantic V2 cross-module contracts)
# ===========================================================================


class CustomerOrder(BaseModel):
    """Represents a customer purchase order generated by the simulator.

    Attributes:
        order_id: Unique order identifier (UUID4 string by default).
        customer_id: Customer placing the order.
        order_date: Date the order was placed.
        items: List of order line-item dictionaries.
        total_amount: Total monetary value of the order (USD).
        currency: ISO 4217 currency code.
        payment_terms: Payment terms string (e.g. ``"Net 30"``).
        status: Current order status — ``"pending"`` at creation.
    """

    order_id: str = Field(default_factory=lambda: str(uuid4()))
    customer_id: str
    order_date: date
    items: List[Dict[str, Any]] = Field(default_factory=list)
    total_amount: float = Field(ge=0.0)
    currency: str = "USD"
    payment_terms: str = "Net 30"
    status: str = "pending"


class CustomerPayment(BaseModel):
    """Represents a customer payment against an outstanding invoice.

    Attributes:
        payment_id: Unique payment identifier (UUID4 string by default).
        customer_id: Customer making the payment.
        invoice_id: Invoice being paid.
        payment_date: Date the payment was received.
        amount_due: Original invoiced amount.
        amount_paid: Actual amount paid (may be less if short-pay).
        payment_method: Payment method string (default ``"check"``).
        is_short_pay: Whether the payment is below the invoiced amount.
        short_pay_reason: Human-readable reason for any short payment.
    """

    payment_id: str = Field(default_factory=lambda: str(uuid4()))
    customer_id: str
    invoice_id: str
    payment_date: date
    amount_due: float = Field(ge=0.0)
    amount_paid: float = Field(ge=0.0)
    payment_method: str = "check"
    is_short_pay: bool = False
    short_pay_reason: Optional[str] = None


class CustomerDispute(BaseModel):
    """Represents a customer dispute raised against an invoice.

    Attributes:
        dispute_id: Unique dispute identifier (UUID4 string by default).
        customer_id: Customer raising the dispute.
        invoice_id: Invoice being disputed.
        dispute_type: Category — ``"pricing"``, ``"quality"``, ``"quantity"``,
            or ``"service"``.
        dispute_amount: Monetary amount under dispute.
        dispute_date: Date the dispute was raised.
        resolution_date: Estimated or actual resolution date (``None`` while open).
        status: Current status — ``"open"`` at creation.
    """

    dispute_id: str = Field(default_factory=lambda: str(uuid4()))
    customer_id: str
    invoice_id: str
    dispute_type: str
    dispute_amount: float = Field(ge=0.0)
    dispute_date: date
    resolution_date: Optional[date] = None
    status: str = "open"


# ===========================================================================
# Tier-to-size mapping used by AmountDistribution
# ===========================================================================

_TIER_TO_SIZE: Dict[str, str] = {
    "strategic": "large",
    "standard": "medium",
    "transactional": "small",
}
"""Maps customer interaction tier to amount-distribution size tier."""

# Valid tiers and profiles for validation
_VALID_TIERS: List[str] = ["strategic", "standard", "transactional"]
_VALID_PROFILES: List[str] = ["excellent", "good", "average", "poor", "problem"]


# ===========================================================================
# CustomerSimulator
# ===========================================================================


class CustomerSimulator:
    """Simulates customer interactions with the ERP system.

    This simulator generates realistic customer orders, payments, and disputes
    by composing statistical distribution models and behaviour profiles.

    Dependencies are injected via the constructor (AAP Section 0.7.1).  All
    public methods are async coroutines with no blocking I/O (AAP Section 0.7.3).

    Args:
        config: Simulator configuration.  Defaults are used when ``None``.
        amount_distribution: Injected ``AmountDistribution`` for order-amount
            sampling by customer tier (log-normal).
        order_frequency_model: Injected ``OrderFrequencyModel`` for Poisson
            daily order counts with day-of-week effects.
        payment_timing_model: Injected ``PaymentTimingModel`` for 5-segment
            mixture model payment dates.
        selection_model: Injected ``SelectionModel`` for 70/30 repeat/new
            product selection and revenue-weighted customer batch selection.
        event_bus: Injected ``EventBus`` for publishing ``TransactionCreated``
            and ``DiscrepancyDetected`` events.
        seed: Optional RNG seed for reproducible simulation runs.
    """

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    def __init__(
        self,
        config: Optional[CustomerSimulatorConfig] = None,
        amount_distribution: Optional[AmountDistribution] = None,
        order_frequency_model: Optional[OrderFrequencyModel] = None,
        payment_timing_model: Optional[PaymentTimingModel] = None,
        selection_model: Optional[SelectionModel] = None,
        event_bus: Optional[EventBus] = None,
        seed: Optional[int] = None,
    ) -> None:
        self._config: CustomerSimulatorConfig = config or CustomerSimulatorConfig()
        self._amount_distribution = amount_distribution
        self._order_frequency_model = order_frequency_model
        self._payment_timing_model = payment_timing_model
        self._selection_model = selection_model
        self._event_bus = event_bus
        self.rng: np.random.RandomState = np.random.RandomState(seed)

        logger.info(
            "customer_simulator_initialized",
            seed=seed,
            default_payment_terms=self._config.default_payment_terms,
            dispute_types=self._config.dispute_types,
        )

    # ------------------------------------------------------------------
    # Order Generation
    # ------------------------------------------------------------------

    async def generate_customer_order(
        self,
        customer: Dict[str, Any],
        simulation_date: date,
        available_products: Optional[List[Dict[str, Any]]] = None,
    ) -> CustomerOrder:
        """Generate a single customer purchase order.

        Determines the customer tier and behaviour profile, samples an order
        amount from ``AmountDistribution`` by size tier, selects products via
        ``SelectionModel`` (70 % repeat / 30 % new), and publishes a
        ``TransactionCreated`` event through the ``EventBus``.

        Args:
            customer: Customer dictionary containing at minimum a
                ``"customer_id"`` key, plus optionally ``"tier"`` /
                ``"customer_tier"``, ``"behavior_profile"``,
                ``"purchase_history"``, and ``"payment_terms"``.
            simulation_date: Current simulation date for the order.
            available_products: Optional product catalogue for line-item
                selection.  Falls back to synthetic placeholders when absent.

        Returns:
            A fully populated ``CustomerOrder`` instance.
        """
        customer_id: str = str(
            customer.get("customer_id", customer.get("id", str(uuid4())))
        )
        tier: str = self._get_customer_tier(customer)
        size_tier: str = _TIER_TO_SIZE.get(tier, "medium")

        # --- Order amount ---------------------------------------------------
        if self._amount_distribution is not None:
            total_amount: float = float(
                self._amount_distribution.sample_customer_order_amount(tier=size_tier)
            )
        else:
            # Fallback: simple random amount within a reasonable range
            total_amount = float(round(self.rng.uniform(500.0, 50_000.0), 2))

        # --- Line items -----------------------------------------------------
        num_items: int = int(
            self.rng.randint(
                self._config.order_line_items_min,
                self._config.order_line_items_max + 1,
            )
        )

        items: List[Dict[str, Any]] = self._build_line_items(
            customer=customer,
            num_items=num_items,
            total_amount=total_amount,
            available_products=available_products,
        )

        # --- Payment terms --------------------------------------------------
        payment_terms: str = str(
            customer.get("payment_terms", self._config.default_payment_terms)
        )

        # --- Assemble order -------------------------------------------------
        order = CustomerOrder(
            customer_id=customer_id,
            order_date=simulation_date,
            items=items,
            total_amount=round(total_amount, 2),
            payment_terms=payment_terms,
            status="pending",
        )

        # --- Publish event --------------------------------------------------
        if self._event_bus is not None:
            event = TransactionCreated(
                payload={
                    "transaction_id": order.order_id,
                    "transaction_type": "customer_order",
                    "amount": order.total_amount,
                    "currency": order.currency,
                    "customer_id": customer_id,
                    "initiator_agent_id": "customer_simulator",
                },
            )
            try:
                await self._event_bus.publish(event)
            except Exception as exc:
                logger.warning(
                    "event_publish_failed",
                    event_type="TransactionCreated",
                    order_id=order.order_id,
                    error=str(exc),
                )

        logger.info(
            "customer_order_generated",
            customer_id=customer_id,
            amount=order.total_amount,
            item_count=num_items,
            tier=tier,
            order_id=order.order_id,
        )

        return order

    async def generate_daily_orders(
        self,
        customers: List[Dict[str, Any]],
        simulation_date: date,
        available_products: Optional[List[Dict[str, Any]]] = None,
    ) -> List[CustomerOrder]:
        """Generate all customer orders for a single simulation day.

        Uses ``OrderFrequencyModel.sample_order_count()`` to determine the
        total order count (Poisson with day-of-week effects), then selects
        which customers place orders via
        ``SelectionModel.select_customers_batch()`` (revenue-weighted).

        Args:
            customers: Pool of customer dictionaries.
            simulation_date: The business date being simulated.
            available_products: Optional product catalogue.

        Returns:
            List of ``CustomerOrder`` objects generated for the day.
        """
        if not customers:
            logger.info(
                "daily_orders_generated",
                date=simulation_date.isoformat(),
                order_count=0,
                reason="empty_customer_pool",
            )
            return []

        # --- Determine order count ------------------------------------------
        if self._order_frequency_model is not None:
            order_count: int = self._order_frequency_model.sample_order_count(
                simulation_date
            )
        else:
            # Fallback: small random count
            order_count = int(
                self.rng.randint(1, max(2, len(customers) // 5 + 1))
            )

        order_count = max(0, order_count)
        if order_count == 0:
            logger.info(
                "daily_orders_generated",
                date=simulation_date.isoformat(),
                order_count=0,
            )
            return []

        # --- Select customers -----------------------------------------------
        if self._selection_model is not None:
            selected_customers: List[Dict[str, Any]] = (
                self._selection_model.select_customers_batch(
                    customers, order_count
                )
            )
        else:
            # Fallback: uniform random selection with replacement
            indices = self.rng.choice(
                len(customers), size=order_count, replace=True
            )
            selected_customers = [customers[int(i)] for i in indices]

        # --- Generate orders ------------------------------------------------
        orders: List[CustomerOrder] = []
        for cust in selected_customers:
            order = await self.generate_customer_order(
                customer=cust,
                simulation_date=simulation_date,
                available_products=available_products,
            )
            orders.append(order)

        logger.info(
            "daily_orders_generated",
            date=simulation_date.isoformat(),
            order_count=len(orders),
        )
        return orders

    # ------------------------------------------------------------------
    # Payment Simulation
    # ------------------------------------------------------------------

    async def simulate_payment(
        self,
        customer: Dict[str, Any],
        invoice: Dict[str, Any],
        simulation_date: date,
    ) -> CustomerPayment:
        """Simulate a customer payment against an outstanding invoice.

        Uses the customer's ``BehaviorProfile`` to determine payment timing
        (via ``PaymentTimingModel``), short-pay probability, and amount.

        Args:
            customer: Customer dictionary with optional ``"behavior_profile"``
                and ``"payment_terms"`` keys.
            invoice: Invoice dictionary containing at minimum ``"invoice_id"``
                and ``"amount"`` (or ``"amount_due"``).
            simulation_date: Current simulation date.

        Returns:
            A ``CustomerPayment`` instance.
        """
        customer_id: str = str(
            customer.get("customer_id", customer.get("id", str(uuid4())))
        )
        invoice_id: str = str(
            invoice.get("invoice_id", invoice.get("id", str(uuid4())))
        )
        amount_due: float = float(
            invoice.get("amount", invoice.get("amount_due", 0.0))
        )

        # --- Behaviour profile ----------------------------------------------
        profile: BehaviorProfile = self._resolve_behavior_profile(customer)

        # --- Invoice date ---------------------------------------------------
        invoice_date_raw = invoice.get(
            "invoice_date", invoice.get("date", simulation_date)
        )
        if isinstance(invoice_date_raw, str):
            invoice_date: date = date.fromisoformat(invoice_date_raw)
        elif isinstance(invoice_date_raw, datetime):
            invoice_date = invoice_date_raw.date()
        elif isinstance(invoice_date_raw, date):
            invoice_date = invoice_date_raw
        else:
            invoice_date = simulation_date

        payment_terms: str = str(
            customer.get("payment_terms", self._config.default_payment_terms)
        )

        # --- Payment date via PaymentTimingModel ----------------------------
        if self._payment_timing_model is not None:
            payment_date: date = self._payment_timing_model.get_payment_date(
                invoice_date=invoice_date,
                payment_terms=payment_terms,
                customer_profile=profile.profile_name,
            )
        else:
            # Fallback: due in 30 days from invoice date
            payment_date = invoice_date + timedelta(days=30)

        # Ensure the payment date is not before the invoice date
        if payment_date < invoice_date:
            payment_date = invoice_date

        # --- Short-pay logic ------------------------------------------------
        is_short_pay: bool = False
        short_pay_reason: Optional[str] = None
        amount_paid: float = amount_due

        short_pay_rate = profile.payment_behavior.short_pay_rate
        if short_pay_rate > 0.0 and self.rng.random() < short_pay_rate:
            is_short_pay = True
            short_pay_pct: float = float(
                self.rng.uniform(
                    self._config.short_pay_percentage_min,
                    self._config.short_pay_percentage_max,
                )
            )
            amount_paid = round(amount_due * (1.0 - short_pay_pct), 2)
            short_pay_reason = (
                f"Short payment of {short_pay_pct:.1%} — customer deducted "
                f"${amount_due - amount_paid:.2f} from invoice {invoice_id}"
            )

        payment = CustomerPayment(
            customer_id=customer_id,
            invoice_id=invoice_id,
            payment_date=payment_date,
            amount_due=round(amount_due, 2),
            amount_paid=round(amount_paid, 2),
            is_short_pay=is_short_pay,
            short_pay_reason=short_pay_reason,
        )

        logger.info(
            "customer_payment_simulated",
            customer_id=customer_id,
            invoice_id=invoice_id,
            amount_paid=payment.amount_paid,
            amount_due=payment.amount_due,
            is_short_pay=is_short_pay,
        )
        return payment

    async def simulate_daily_payments(
        self,
        customers: List[Dict[str, Any]],
        outstanding_invoices: List[Dict[str, Any]],
        simulation_date: date,
    ) -> List[CustomerPayment]:
        """Simulate all customer payments due on a given simulation date.

        Filters *outstanding_invoices* to those whose expected payment date
        falls on or before *simulation_date*, then simulates each payment.

        Args:
            customers: Pool of customer dictionaries.
            outstanding_invoices: Invoices awaiting payment.
            simulation_date: The business date being simulated.

        Returns:
            List of ``CustomerPayment`` instances for payments due today.
        """
        if not outstanding_invoices:
            return []

        # Build customer lookup for efficient matching
        customer_map: Dict[str, Dict[str, Any]] = {}
        for cust in customers:
            cid = str(cust.get("customer_id", cust.get("id", "")))
            if cid:
                customer_map[cid] = cust

        payments: List[CustomerPayment] = []
        for inv in outstanding_invoices:
            # Determine the invoice's expected payment / due date
            due_date_raw = inv.get(
                "payment_due_date",
                inv.get("due_date", inv.get("expected_payment_date")),
            )
            if due_date_raw is None:
                # If no explicit due date, compute from invoice date + 30d
                inv_date_raw = inv.get("invoice_date", inv.get("date"))
                if isinstance(inv_date_raw, str):
                    inv_date = date.fromisoformat(inv_date_raw)
                elif isinstance(inv_date_raw, date):
                    inv_date = inv_date_raw
                else:
                    continue
                due_date = inv_date + timedelta(days=30)
            else:
                if isinstance(due_date_raw, str):
                    due_date = date.fromisoformat(due_date_raw)
                elif isinstance(due_date_raw, datetime):
                    due_date = due_date_raw.date()
                elif isinstance(due_date_raw, date):
                    due_date = due_date_raw
                else:
                    continue

            if due_date > simulation_date:
                continue

            cust_id = str(inv.get("customer_id", inv.get("id", "")))
            cust = customer_map.get(cust_id, {"customer_id": cust_id})

            payment = await self.simulate_payment(
                customer=cust,
                invoice=inv,
                simulation_date=simulation_date,
            )
            payments.append(payment)

        return payments

    # ------------------------------------------------------------------
    # Dispute Handling
    # ------------------------------------------------------------------

    async def simulate_dispute(
        self,
        customer: Dict[str, Any],
        invoice: Dict[str, Any],
        simulation_date: date,
    ) -> Optional[CustomerDispute]:
        """Probabilistically simulate a customer dispute for an invoice.

        Dispute probability is driven by the customer's ``BehaviorProfile``
        ``dispute_rate`` field.  When triggered, a ``DiscrepancyDetected``
        event is published via the ``EventBus``.

        Args:
            customer: Customer dictionary.
            invoice: Invoice dictionary (must contain ``"invoice_id"`` and
                ``"amount"`` or ``"amount_due"``).
            simulation_date: Current simulation date.

        Returns:
            A ``CustomerDispute`` instance if triggered, otherwise ``None``.
        """
        profile: BehaviorProfile = self._resolve_behavior_profile(customer)

        # Check whether a dispute occurs
        dispute_rate = profile.payment_behavior.dispute_rate
        if dispute_rate <= 0.0 or self.rng.random() >= dispute_rate:
            return None

        customer_id: str = str(
            customer.get("customer_id", customer.get("id", str(uuid4())))
        )
        invoice_id: str = str(
            invoice.get("invoice_id", invoice.get("id", str(uuid4())))
        )
        invoice_amount: float = float(
            invoice.get("amount", invoice.get("amount_due", 0.0))
        )

        # --- Dispute type ---------------------------------------------------
        dispute_type: str = str(self.rng.choice(self._config.dispute_types))

        # --- Dispute amount (partial or full) --------------------------------
        dispute_fraction: float = float(self.rng.uniform(0.1, 1.0))
        dispute_amount: float = round(invoice_amount * dispute_fraction, 2)

        # --- Estimated resolution date ---------------------------------------
        resolution_days: int = int(
            self.rng.randint(
                self._config.dispute_resolution_days_min,
                self._config.dispute_resolution_days_max + 1,
            )
        )
        resolution_date: date = simulation_date + timedelta(days=resolution_days)

        dispute = CustomerDispute(
            customer_id=customer_id,
            invoice_id=invoice_id,
            dispute_type=dispute_type,
            dispute_amount=dispute_amount,
            dispute_date=simulation_date,
            resolution_date=resolution_date,
            status="open",
        )

        # --- Publish event --------------------------------------------------
        if self._event_bus is not None:
            event = DiscrepancyDetected(
                payload={
                    "discrepancy_type": f"customer_dispute_{dispute_type}",
                    "transaction_id": invoice_id,
                    "severity": "medium",
                    "details": (
                        f"Customer {customer_id} disputes "
                        f"${dispute_amount:.2f} on invoice "
                        f"{invoice_id} ({dispute_type})"
                    ),
                    "detected_by_agent_id": "customer_simulator",
                    "dispute_id": dispute.dispute_id,
                },
            )
            try:
                await self._event_bus.publish(event)
            except Exception as exc:
                logger.warning(
                    "event_publish_failed",
                    event_type="DiscrepancyDetected",
                    dispute_id=dispute.dispute_id,
                    error=str(exc),
                )

        logger.warning(
            "customer_dispute_created",
            customer_id=customer_id,
            invoice_id=invoice_id,
            dispute_type=dispute_type,
            amount=dispute_amount,
            resolution_days=resolution_days,
            dispute_id=dispute.dispute_id,
        )
        return dispute

    async def check_disputes_for_invoices(
        self,
        customer: Dict[str, Any],
        invoices: List[Dict[str, Any]],
        simulation_date: date,
    ) -> List[CustomerDispute]:
        """Check for disputes across multiple invoices for a customer.

        Iterates over each invoice and calls :meth:`simulate_dispute`.  Only
        non-``None`` results are included in the returned list.

        Args:
            customer: Customer dictionary.
            invoices: List of invoice dictionaries.
            simulation_date: Current simulation date.

        Returns:
            List of ``CustomerDispute`` instances for triggered disputes.
        """
        disputes: List[CustomerDispute] = []
        for inv in invoices:
            dispute = await self.simulate_dispute(
                customer=customer,
                invoice=inv,
                simulation_date=simulation_date,
            )
            if dispute is not None:
                disputes.append(dispute)
        return disputes

    # ------------------------------------------------------------------
    # Private Utility Methods
    # ------------------------------------------------------------------

    def _get_customer_tier(self, customer: Dict[str, Any]) -> str:
        """Extract the customer interaction tier from a customer dictionary.

        Looks for ``"tier"`` or ``"customer_tier"`` keys, normalises to lower
        case, and validates against the canonical set.  Falls back to
        ``"standard"`` if absent or invalid.

        Args:
            customer: Customer dictionary.

        Returns:
            One of ``"strategic"``, ``"standard"``, ``"transactional"``.
        """
        raw_tier: str = str(
            customer.get("tier", customer.get("customer_tier", "standard"))
        ).lower().strip()
        if raw_tier in _VALID_TIERS:
            return raw_tier
        return "standard"

    def _get_customer_profile(self, customer: Dict[str, Any]) -> str:
        """Extract the payment quality profile name from a customer dictionary.

        Checks for a nested ``"behavior_profile"`` object with a
        ``"profile_name"`` key, or a top-level ``"profile"`` /
        ``"profile_name"`` field.  Falls back to ``"average"`` when
        unavailable.

        Args:
            customer: Customer dictionary.

        Returns:
            One of ``"excellent"``, ``"good"``, ``"average"``, ``"poor"``,
            ``"problem"``.
        """
        # Try nested behavior profile
        bp = customer.get("behavior_profile")
        if isinstance(bp, BehaviorProfile):
            return bp.profile_name
        if isinstance(bp, dict):
            name = str(bp.get("profile_name", "average")).lower().strip()
            if name in _VALID_PROFILES:
                return name

        # Try top-level keys
        for key in ("profile_name", "profile", "payment_profile"):
            val = customer.get(key)
            if val is not None:
                name = str(val).lower().strip()
                if name in _VALID_PROFILES:
                    return name

        return "average"

    def _resolve_behavior_profile(
        self, customer: Dict[str, Any]
    ) -> BehaviorProfile:
        """Resolve a full ``BehaviorProfile`` for a customer.

        Checks for an injected ``BehaviorProfile`` instance first, then
        constructs one from dictionary data, and finally falls back to a
        predefined template keyed by profile name.

        Args:
            customer: Customer dictionary.

        Returns:
            A ``BehaviorProfile`` instance.
        """
        bp = customer.get("behavior_profile")
        if isinstance(bp, BehaviorProfile):
            return bp
        if isinstance(bp, dict):
            try:
                return BehaviorProfile(**bp)
            except Exception:
                pass

        profile_name = self._get_customer_profile(customer)
        template = CUSTOMER_PROFILE_TEMPLATES.get(profile_name)
        if template is not None:
            return template
        return CUSTOMER_PROFILE_TEMPLATES.get("average", BehaviorProfile())

    def _build_line_items(
        self,
        customer: Dict[str, Any],
        num_items: int,
        total_amount: float,
        available_products: Optional[List[Dict[str, Any]]] = None,
    ) -> List[Dict[str, Any]]:
        """Build a list of order line-item dictionaries.

        Distributes *total_amount* across *num_items* line items using a
        Dirichlet distribution for realistic variation.  Product selection
        uses the ``SelectionModel`` when available.

        Args:
            customer: Customer dictionary (for purchase history lookup).
            num_items: Number of line items to generate.
            total_amount: Total order amount to distribute.
            available_products: Optional product catalogue.

        Returns:
            List of line-item dictionaries.
        """
        if num_items <= 0:
            return []

        items: List[Dict[str, Any]] = []

        # Dirichlet distribution for realistic per-item amounts
        raw_weights = self.rng.dirichlet(np.ones(num_items))
        item_amounts = [round(float(w * total_amount), 2) for w in raw_weights]

        # Correct rounding residual on the last item
        rounding_diff = round(total_amount - sum(item_amounts), 2)
        item_amounts[-1] = round(item_amounts[-1] + rounding_diff, 2)

        purchase_history: Optional[List[Dict[str, Any]]] = customer.get(
            "purchase_history"
        )

        for idx in range(num_items):
            quantity: int = max(1, int(self.rng.randint(1, 100)))
            item: Dict[str, Any] = {
                "line_number": idx + 1,
                "quantity": quantity,
                "unit_price": round(item_amounts[idx] / max(1, quantity), 2),
                "amount": item_amounts[idx],
            }

            # Product selection via SelectionModel (70/30 repeat/new)
            if available_products and self._selection_model is not None:
                try:
                    product = self._selection_model.select_product(
                        available_products=available_products,
                        purchase_history=purchase_history,
                    )
                    item["product_id"] = product.get(
                        "product_id",
                        product.get("id", f"PROD-{idx + 1}"),
                    )
                    item["product_name"] = product.get(
                        "name",
                        product.get("product_name", f"Product {idx + 1}"),
                    )
                except Exception:
                    item["product_id"] = f"PROD-{idx + 1}"
                    item["product_name"] = f"Product {idx + 1}"
            elif available_products:
                # No selection model — pick randomly from catalogue
                prod_idx = int(self.rng.randint(0, len(available_products)))
                product = available_products[prod_idx]
                item["product_id"] = product.get(
                    "product_id",
                    product.get("id", f"PROD-{idx + 1}"),
                )
                item["product_name"] = product.get(
                    "name",
                    product.get("product_name", f"Product {idx + 1}"),
                )
            else:
                item["product_id"] = f"PROD-{idx + 1}"
                item["product_name"] = f"Product {idx + 1}"

            items.append(item)

        return items
